modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="dappled_spawns"
version="1.0.0"
displayName="Dappled Forest Spawns Mod"
description="Forced clean spawn parameters for Alex's Mobs and Primal Deer."
